### PR TITLE
feat!: a big rewrite

### PR DESCRIPTION
**Pull request by Jack-Works**
# Breaking changes

- Webpack 4 no longer supported
- Node 14- no longer supported
- `webpack-target-webextension/lib/background` removed.

# Feature

- Support code splitting in Manifest V3
- Support async module loading in manifest V3

# Other

- Add tests

# TODO

- [x] Rewrite README
- [x] Rewrite examples
- [x] Write migration guide

### CODE REVIEW

**Comment by Jack-Works** [comment]
@crimx hi please enable GitHub actions for this repo

**Comment by Jack-Works** [comment]
@crimx hi please review this PR

**Comment by Jack-Works** [comment]
hello? @crimx

**Review by crimx — APPROVED** [review]
@Jack-Works Sorry I was on vacation. Looks good!

**Comment by crimx** [comment]
Do you think it's ready for 1.0.0?

**Comment by Jack-Works** [comment]
> Do you think it's ready for 1.0.0?

Let me test it in my woking repo first.

**Comment by Jack-Works** [comment]
> Do you think it's ready for 1.0.0?

@crimx Hi! I've tested it in our project and fixes some bugs. I think it's time to release 1.0.0

**Comment by crimx** [comment]
Great! Published.

**Pull request merged**
