### PR TITLE
fix: add workaround for chrome bug 816121

### PR DESCRIPTION
**Pull request by Jack-Works**
a dirty hack to workaround Chrome bug https://bugs.chromium.org/p/chromium/issues/detail?id=816121

this dirty hack tries to detect this bug and fix it by calling the classic loader, therefore you must have the correct permissions (like "scripting" in mv3) and host_permissions of the target origin.

you can see the document of classic loader in the readme of this project.

### CODE REVIEW

**Comment by fregante** [comment]
Thank you for the quick fix! I'll try it tomorrow or early this week

**Comment by fregante** [comment]
Screenshot 1

**Comment by Jack-Works** [comment]
yes, you need to specify a background entry (background page in mv2 or service worker in mv3) in the config to use the classic loader @fregante

**Comment by fregante** [comment]
I tried: https://github.com/pixiebrix/pixiebrix-extension/pull/7374

The error disappeared, but the original chunk error returned

Screenshot 13


However I saw this error in the background, I think you're just missing `matchAboutBlank: true` in your `executeScript`, we already have the `<all_urls>` permission.

Screenshot 14

**Comment by fregante** [comment]
> I think you're just missing `matchAboutBlank: true`

Yep, that fixes it :)

**Comment by fregante** [comment]
I'm seeing this in the background though, which breaks it for the rest of the extension:

Screenshot 20
Screenshot 21

**Comment by Jack-Works** [comment]
hello, I cannot reproduce. It works on my side. Here is my setup.

> webpack.config.js

```js
const WebExtension = require('webpack-target-webextension')
const webpack = require('webpack')
const { join } = require('path')

/** @returns {webpack.Configuration} */
const config = (a, env) => ({
  module: {
    rules: [],
  },
  entry: {
    bg: join(__dirname, './bg-src.js'),
    cs: join(__dirname, './cs-src.js'),
  },
  output: {
    path: join(__dirname, './dist'),
    publicPath: '/dist/',
    environment: {
      dynamicImport: true,
    },
  },
  plugins: [
    new WebExtension({
      background: { serviceWorkerEntry: 'bg' },
    }),
  ].filter(Boolean),
  devServer: {},
  optimization: {
    minimize: false,
  },
})
module.exports = config
```

> bg-src.js

```js
setTimeout(() => {
  import('./secondary.js')
}, 200)
```

> cs-src.js

```js
if (location.href.startsWith('about')) {
  console.log(location.href)
  import('./secondary.js')
  import('./secondary-2.js')
}
```

> manifest.json

```json
{
  "name": "sandbox iframe",
  "version": "1.0.7",
  "manifest_version": 3,
  "description": "Demo extension",
  "permissions": ["scripting", "activeTab"],
  "host_permissions": ["http://127.0.0.1:8080/*"],
  "background": {
    "service_worker": "dist/bg.js"
  },
  "web_accessible_resources": [
    {
      "resources": ["*.js"],
      "matches": ["<all_urls>"]
    }
  ],
  "content_scripts": [
    {
      "matches": ["*://*/*"],
      "js": ["dist/cs.js"],
      "all_frames": true,
      "match_about_blank": true
    }
  ]
}
```

> secondary.js

```js
console.log('secondary')
```

> secondary-2.js

```js
console.log('secondary 2')
```

> test.html

```html
<html>
<body>
  <!-- srcdoc or src, same issue-->
  <iframe srcdoc="Hello world!" sandbox>
</body>
</html>
```

**Comment by fregante** [comment]
Could it be because it's a nested import()? i.e. a import()'d module imports another module.

I'll try again today

**Comment by fregante** [comment]
Ok I think I found the issue:

```js
new WebExtensionTarget({
  weakRuntimeCheck: true,
  background: {
    pageEntry: "background",
    serviceWorkerEntry: "background",
  },
}),
```

My build can generate either MV2 or MV3, depending on the `MV` env, so I set both to the same entry name.

However of course that caused worker code to appear in the background page.

I'll keep testing…

**Comment by fregante** [comment]
I can confirm that the MV2 version appears to work perfectly, however the MV3 version seems to conflict with `mini-css-extract-plugin`, in the background worker:

Screenshot

I don't know if this is an issue with this PR or if it's due to the addition of `serviceWorkerEntry` to the config.

I'll keep testing, but if you want to see it yourself:

```sh
# check out https://github.com/pixiebrix/pixiebrix-extension/pull/7374
npm install
MV=3 npm run watch:webpack # or build:webpack, slower
# then run the extension from dist/
```

**Comment by fregante** [comment]
Ok I think that issue already existed, so this PR is done and ready 🥳 

I'll look into the to that `loadStylesheet` error and open an issue.

**Comment by fregante** [comment]
BTW, if you want to test frames, srcdoc and sandbox, here you'll find plenty of composable links:

https://github.com/fregante/ephiframe

In this specific case, this link loads both a sandboxed and a non-sandboxed `src` iframes:

- https://more-ephiframe.vercel.app/Outer?sandbox=&iframe=./Full-sandbox&iframe=./No-sandbox

**Comment by Jack-Works** [comment]
> My build can generate either MV2 or MV3, depending on the MV env, so I set both to the same entry name. However that caused worker code to appear in the background page (hence the importScripts not defined error)

I didn't expect `pageEntry` and `serviceWorkerEntry` can be the same. I'll investigate this later, try to make it work, and if not, give a warning in this case.

**Comment by fregante** [comment]
Sounds good, it could be done separately since it's unrelated to frames/loading. 

But this is working well for us already. ✅

**Pull request merged**
